# Generated by Django 4.1 on 2022-10-04 15:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.validators


class Migration(migrations.Migration):

    replaces = [('shop', '0001_initial'), ('shop', '0002_alter_product_picture_url'), ('shop', '0003_card'), ('shop', '0004_product_amount'), ('shop', '0005_remove_card_quantuty_card_quantity'), ('shop', '0006_card_card_id'), ('shop', '0007_alter_card_price_alter_card_product_and_more'), ('shop', '0008_alter_card_quantity'), ('shop', '0009_card_unique_card_product'), ('shop', '0010_alter_card_quantity'), ('shop', '0011_alter_card_quantity'), ('shop', '0012_shoprequest'), ('shop', '0013_shoprequest_comment_shoprequest_is_delivered')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('picture_url', models.ImageField(upload_to='images/', verbose_name='Фото товара')),
                ('amount', models.CharField(choices=[('kg', 'кг'), ('pcs', 'шт')], default='kg', max_length=3, verbose_name='Мера (кг или шт)')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
                ('quantity', models.IntegerField(null=True, validators=[shop.validators.validate_card_quantity], verbose_name='Колличество')),
                ('card_id', models.CharField(default=0, max_length=40, verbose_name='Идентификатор корзины')),
            ],
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('product', 'card_id'), name='unique_card_product', violation_error_message='Card can only have one instance of a product'),
        ),
        migrations.AlterField(
            model_name='card',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[shop.validators.validate_card_quantity], verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='card',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[shop.validators.validate_card_quantity], verbose_name='Колличество'),
        ),
        migrations.CreateModel(
            name='ShopRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=40, verbose_name='Идентификатор корзины')),
                ('name', models.CharField(help_text='Введите имя по которому к вам можно оброщатся', max_length=30, verbose_name='Имя покупателя')),
                ('phone', models.CharField(help_text='Введите номер вашего мобильного телефона', max_length=20, validators=[django.core.validators.RegexValidator(message='Введите номер мобильного телефона', regex='/(?:\\+|\\d)[\\d\\-\\(\\) ]{9,}\\d/g')], verbose_name='Номер телефона покупателя')),
                ('address', models.CharField(help_text='Введите адрес по которому доставить покупки', max_length=300, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий (если необходим)', max_length=300, null=True, verbose_name='Комментарий покупателя')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Доставка выполнена?')),
            ],
        ),
    ]
