# Generated by Django 4.1 on 2022-09-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture_url',
            field=models.ImageField(upload_to='images/', verbose_name='Фото товара'),
        ),
    ]
