# Generated by Django 4.1 on 2022-09-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.CharField(choices=[('kg', 'кг'), ('pcs', 'шт')], default='kg', max_length=3, verbose_name='Мера (кг или шт)'),
        ),
    ]
