# Generated by Django 4.1 on 2022-09-28 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='quantuty',
        ),
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Колличество'),
            preserve_default=False,
        ),
    ]
