# Generated by Django 4.1 on 2022-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_card_quantuty_card_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.CharField(default=0, max_length=40, verbose_name='Идентификатор корзины'),
            preserve_default=False,
        ),
    ]
