# Generated by Django 4.1 on 2022-10-02 23:45

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_card_price_alter_card_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(null=True, validators=[shop.validators.validate_card_quantity], verbose_name='Колличество'),
        ),
    ]
