# Generated by Django 4.1 on 2022-11-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_options_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заявки'),
        ),
    ]
