# Generated by Django 4.1 on 2022-11-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shoprequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprequest',
            name='request_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата заявки'),
        ),
    ]
