# Generated by Django 4.1 on 2022-10-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_card_quantity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('product', 'card_id'), name='unique_card_product', violation_error_message='Card can only have one instance of a product'),
        ),
    ]
