# Generated by Django 4.1 on 2022-10-04 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_card_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=40, verbose_name='Идентификатор корзины')),
                ('name', models.CharField(help_text='Введите имя по которому к вам можно оброщатся', max_length=30, verbose_name='Имя покупателя')),
                ('phone', models.CharField(help_text='Введите номер вашего мобильного телефона', max_length=20, validators=[django.core.validators.RegexValidator(message='Введите номер мобильного телефона', regex='/(?:\\+|\\d)[\\d\\-\\(\\) ]{9,}\\d/g')], verbose_name='Номер телефона покупателя')),
                ('address', models.CharField(help_text='Введите адрес по которому доставить покупки', max_length=300, verbose_name='Адрес доставки')),
            ],
        ),
    ]
