# Generated by Django 4.1 on 2022-10-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shoprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprequest',
            name='comment',
            field=models.TextField(blank=True, help_text='Введите комментарий (если необходим)', max_length=300, null=True, verbose_name='Комментарий покупателя'),
        ),
        migrations.AddField(
            model_name='shoprequest',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Доставка выполнена?'),
        ),
    ]
