# Generated by Django 4.1 on 2022-10-30 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_squashed_0013_shoprequest_comment_shoprequest_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Товар доступен?'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(max_length=40, verbose_name='Идентификатор корзины'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='comment',
            field=models.TextField(blank=True, help_text='Введите комментарий (если необходим)', max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='name',
            field=models.CharField(help_text='Введите имя по которому к вам можно обращатся', max_length=30, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='phone',
            field=models.CharField(help_text='Введите номер вашего мобильного телефона', max_length=20, validators=[django.core.validators.RegexValidator(message='Введите номер мобильного телефона', regex='(\\+7|8)[- _]*\\(?[- _]*(\\d{3}[- _]*\\)?([- _]*\\d){7}|\\d\\d[- _]*\\d\\d[- _]*\\)?([- _]*\\d){6})')], verbose_name='Номер телефона для связи'),
        ),
    ]
